Repository kube-rs/kube, pull requests merged in 2021-12, with the labels that each got.

#739 Remove TypeMeta fields from derived kind objects
  CHANGELOG.md
  kube-derive/src/custom_resource.rs
  kube-derive/tests/crd_schema_test.rs
Labels: derive

#757 Add `DeleteParams` constructors for easily setting `PropagationPolicy`
  CHANGELOG.md
  deny.toml
  examples/job_api.rs
  kube-core/src/params.rs
Labels: changelog-add

#758 Continued coverage improvements (runtime::wait)
  .github/workflows/coverage.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  governance.md
  kube-client/src/lib.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/wait.rs
  kube/src/lib.rs
Labels: changelog-exclude

#761 fix clippy must_uses
  Makefile
  kube-client/src/discovery/mod.rs
  kube-core/src/admission.rs
  kube-core/src/dynamic.rs
  kube-core/src/object.rs
  kube-core/src/params.rs
  kube-core/src/resource.rs
  kube-core/src/subresource.rs
  kube-runtime/src/controller/mod.rs
Labels: changelog-exclude

#760 Add Serialize to ObjecList and add field-selector and jsonpath example
  examples/Cargo.toml
  examples/README.md
  examples/dynamic_jsonpath.rs
  kube-core/src/object.rs
Labels: changelog-add

#703 Add backoff handling for watcher and Controller - for #577
  CHANGELOG.md
  examples/Cargo.toml
  examples/dynamic_jsonpath.rs
  examples/dynamic_pod.rs
  examples/dynamic_watcher.rs
  examples/event_watcher.rs
  examples/job_api.rs
  examples/node_watcher.rs
  examples/pod_watcher.rs
  kube-client/src/discovery/mod.rs
  kube-client/src/lib.rs
  kube-core/src/dynamic.rs
  kube-core/src/object.rs
  kube-core/src/params.rs
  kube-core/src/subresource.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/backoff_reset_timer.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_backoff.rs
  kube-runtime/src/watcher.rs
  kube/src/lib.rs
Labels: changelog-add

#765 Add config for generated release notes
  .github/release.yml
Labels: changelog-exclude

#762 Implement cordon/uncordon for Node
  kube-client/src/api/util.rs
  kube-core/src/util.rs
Labels: changelog-add

#770 Install OpenSSL library in Windows CI workflow using Chocolatey
  .github/workflows/ci.yml
Labels: changelog-exclude

#764 Export Version priority parser with Ord impls in kube_core
  kube-client/src/discovery/apigroup.rs
  kube-client/src/discovery/mod.rs
  kube-client/src/discovery/version.rs
  kube-core/src/lib.rs
  kube-core/src/version.rs
Labels: changelog-add
