Repository kube-rs/kube, pull requests merged in 2022-04, with the labels that each got.

#866 Fix the default TLS for `kube`
  kube/Cargo.toml
Labels: changelog-exclude

#867 Move adopters file to website
  ADOPTERS.md
  README.md
Labels: changelog-exclude

#868 Canonicalise more webpage docs + fix relative links
  CHANGELOG.md
  CONTRIBUTING.md
  SECURITY.md
  architecture.md
  governance.md
  maintainers.md
Labels: docs, changelog-exclude

#871 change event recorder cluster namespace to kube-system
  kube-runtime/src/events.rs
Labels: changelog-change

#875 Fix in-cluster kube_host_port generation for IPv6
  kube-client/src/config/incluster_config.rs
Labels: changelog-fix

#876 Switch to kubernetes cluster dns for incluster url everywhere
  kube-client/src/config/incluster_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-change

#878 Fix minor certificates typo in Config struct
  kube-client/src/config/mod.rs
Labels: changelog-exclude
