Repository kube-rs/kube, pull requests merged in 2022-05, with the labels that each got.

#890 Remove deprecated legacy crd v1beta1
  .github/workflows/ci.yml
  Makefile
  examples/Cargo.toml
  examples/README.md
  examples/crd_api.rs
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-core/src/crd.rs
  kube/Cargo.toml
Labels: changelog-remove

#889 Allow merging multi-version CRDs into a single schema
  .devcontainer/devcontainer.json
  examples/Cargo.toml
  examples/crd_derive_multi.rs
  kube-client/src/error.rs
  kube-core/Cargo.toml
  kube-core/src/crd.rs
  kube-derive/src/lib.rs
Labels: changelog-add

#894 Fix Rust 1.60 clippy lint warnings
  examples/crd_derive_multi.rs
  examples/pod_cp.rs
  examples/pod_exec.rs
  kube-client/src/lib.rs
  kube-core/src/schema.rs
  kube-derive/tests/crd_enum_test.rs
Labels: changelog-exclude

#885 Add a kubectl like example
  examples/Cargo.toml
  examples/README.md
  examples/admission_controller.rs
  examples/configmap_reflector.rs
  examples/configmap_watcher.rs
  examples/configmapgen_controller.rs
  examples/crd_api.rs
  examples/crd_apply.rs
  examples/crd_derive.rs
  examples/crd_derive_multi.rs
  examples/crd_derive_no_schema.rs
  examples/crd_reflector.rs
  examples/custom_client.rs
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
  examples/deployment_reflector.rs
  examples/dynamic_api.rs
  examples/dynamic_jsonpath.rs
  examples/dynamic_pod.rs
  examples/dynamic_watcher.rs
  examples/event_watcher.rs
  examples/job_api.rs
  examples/kubectl.rs
  examples/log_stream.rs
  examples/multi_watcher.rs
  examples/node_reflector.rs
  examples/node_watcher.rs
  examples/pod_api.rs
  examples/pod_attach.rs
  examples/pod_cp.rs
  examples/pod_evict.rs
  examples/pod_exec.rs
  examples/pod_portforward.rs
  examples/pod_portforward_bind.rs
  examples/pod_portforward_hyper_http.rs
  examples/pod_reflector.rs
  examples/pod_shell.rs
  examples/pod_watcher.rs
  examples/secret_reflector.rs
  examples/secret_syncer.rs
Labels: changelog-exclude

#895 Bump CI to k8s-openapi v1_23
  Makefile
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  release.toml
Labels: changelog-exclude

#896 Add GroupVersion::with_kind and TypeMeta -> GroupVersionKind converters
  kube-core/src/gvk.rs
Labels: changelog-add

#898 Add managed_fields accessors to ResourceExt
  kube-core/src/resource.rs
  kube/src/lib.rs
Labels: changelog-add

#888 Add ResourceExt::creation_timestamp
  examples/kubectl.rs
  kube-core/src/resource.rs
Labels: changelog-add

#892 Support lowercase http_proxy & https_proxy evars
  kube-client/src/config/file_loader.rs
Labels: changelog-add

#903 Replace `make` as a script running with `just`
  .devcontainer/Dockerfile
  CONTRIBUTING.md
  Makefile
  e2e/README.md
  justfile
Labels: changelog-exclude

#897 Extend kubectl example with apply + edit and example improvements
  examples/Cargo.toml
  examples/README.md
  examples/configmap_reflector.rs
  examples/configmap_watcher.rs
  examples/crd_api.rs
  examples/crd_apply.rs
  examples/crd_derive_no_schema.rs
  examples/crd_derive_schema.rs
  examples/crd_reflector.rs
  examples/deployment_reflector.rs
  examples/dynamic_api.rs
  examples/job_api.rs
  examples/kubectl.rs
  examples/log_stream.rs
  examples/multi_watcher.rs
  examples/pod_attach.rs
  examples/pod_cp.rs
  examples/pod_evict.rs
  examples/pod_exec.rs
  examples/pod_portforward.rs
  examples/pod_portforward_bind.rs
  examples/pod_portforward_hyper_http.rs
  examples/pod_reflector.rs
  examples/pod_shell.rs
  examples/pod_watcher.rs
  examples/secret_reflector.rs
Labels: changelog-exclude

#906 Rename unreleased watcher ext methods slightly
  README.md
  examples/configmap_reflector.rs
  examples/crd_reflector.rs
  examples/dynamic_watcher.rs
  examples/event_watcher.rs
  examples/kubectl.rs
  examples/multi_watcher.rs
  examples/node_reflector.rs
  examples/node_watcher.rs
  examples/pod_watcher.rs
  examples/secret_reflector.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/event_flatten.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/watch_ext.rs
  kube-runtime/src/watcher.rs
  kube/src/lib.rs
Labels: changelog-exclude

#907 Add Event::modify + reflector::store helpers
  examples/Cargo.toml
  examples/README.md
  examples/configmap_reflector.rs
  examples/crd_reflector.rs
  examples/node_reflector.rs
  examples/pod_reflector.rs
  examples/secret_reflector.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/watcher.rs
Labels: changelog-add

#909 Update docs and finalize for 0.72.0
  README.md
Labels: changelog-exclude

#910 Replace runtime::controller::Context with Arc
  examples/configmapgen_controller.rs
  examples/kubectl.rs
  examples/secret_syncer.rs
  kube-runtime/src/controller/mod.rs
Labels: runtime, changelog-change

#877 runtime: Return the object from `await_condition`
  kube-runtime/src/wait.rs
Labels: runtime, changelog-change

#887 Add Discovery::groups_alphabetical following kubectl sort order
  kube-client/src/discovery/mod.rs
  kube/src/lib.rs
Labels: changelog-add

#916 Bump k8s-openapi to 0.15 for kubernetes v1_24 and bump MSRV to 1.60
  .devcontainer/Dockerfile
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  release.toml
  scripts/msrv.sh
Labels: changelog-change

#920 Remove `#[kube(apiextensions)]` flag from `kube-derive`
  examples/crd_derive_schema.rs
  kube-core/src/crd.rs
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_enum_test.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-remove

#919 Document every public derived fn from kube-derive
  examples/crd_apply.rs
  kube-derive/src/custom_resource.rs
Labels: changelog-fix
