Repository kube-rs/kube, pull requests merged in 2022-12, with the labels that each got.

#1096 exec: ensure certs always end with a new line
  kube-client/src/client/config_ext.rs
Labels: changelog-fix

#1099 cargo clippy --fix for uninlined fmt args
  clippy.toml
  examples/crd_derive.rs
  examples/crd_derive_schema.rs
  examples/kubectl.rs
  examples/node_watcher.rs
  examples/pod_cp.rs
  examples/pod_exec.rs
  examples/pod_shell_crossterm.rs
  examples/secret_syncer.rs
  kube-client/src/api/entry.rs
  kube-client/src/api/util/mod.rs
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/middleware/base_uri.rs
  kube-client/src/client/middleware/mod.rs
  kube-client/src/client/mod.rs
  kube-client/src/config/file_config.rs
  kube-client/src/discovery/apigroup.rs
  kube-client/src/discovery/parse.rs
  kube-client/src/lib.rs
  kube-core/src/discovery.rs
  kube-core/src/gvk.rs
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-core/src/resource.rs
  kube-core/src/schema.rs
  kube-core/src/subresource.rs
  kube-core/src/watch.rs
  kube-derive/src/custom_resource.rs
  kube-runtime/src/utils/mod.rs
Labels: changelog-exclude

#1077 fix: align kube-rs with client-go config parsing
  kube-client/src/client/auth/mod.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/file_loader.rs
  kube-client/src/config/mod.rs
Labels: changelog-fix

#1095 [windows] skip window creation on auth exec
  kube-client/src/client/auth/mod.rs
Labels: changelog-change

#1100 Change `Kubeconfig::merge` fn to public.
  kube-client/src/config/file_config.rs
Labels: changelog-add

#1101 Return error from `watcher` when kinds do not support watch
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1083 Fix interactivity in auth exec
  kube-client/src/client/auth/mod.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-add

#1105 Remove deprecated `ResourceExt::name`
  kube-client/src/api/core_methods.rs
  kube-client/src/discovery/apigroup.rs
  kube-client/src/discovery/mod.rs
  kube-client/src/discovery/oneshot.rs
  kube-client/src/lib.rs
  kube-core/src/resource.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/watcher.rs
  kube/src/lib.rs
Labels: changelog-remove

#1104 Add `Config::tls_server_name` and validate when using rustls
  kube-client/Cargo.toml
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/mod.rs
Labels: config, rustls, changelog-change

#1111 reflector: add some helper function to the store
  kube-runtime/src/reflector/store.rs
Labels: runtime, changelog-add

#1112 fix shell exec exiting message loop when terminalSizeReceiver is dropped
  kube-client/src/api/remote_command.rs
Labels: changelog-fix
