Repository kube-rs/kube, pull requests merged in 2022-07, with the labels that each got.

#945 Deprecate ResourceExt::name in favour of safe name_* alternatives
  e2e/boot.rs
  examples/admission_controller.rs
  examples/crd_api.rs
  examples/crd_apply.rs
  examples/crd_reflector.rs
  examples/custom_client.rs
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
  examples/dynamic_api.rs
  examples/dynamic_pod.rs
  examples/dynamic_watcher.rs
  examples/kubectl.rs
  examples/multi_watcher.rs
  examples/node_reflector.rs
  examples/node_watcher.rs
  examples/pod_api.rs
  examples/pod_attach.rs
  examples/pod_cp.rs
  examples/pod_evict.rs
  examples/pod_exec.rs
  examples/pod_portforward.rs
  examples/pod_portforward_bind.rs
  examples/pod_portforward_hyper_http.rs
  examples/pod_reflector.rs
  examples/pod_shell.rs
  examples/pod_watcher.rs
  examples/secret_reflector.rs
  kube-core/src/admission.rs
  kube-core/src/params.rs
  kube-core/src/resource.rs
  kube-runtime/src/reflector/object_ref.rs
Labels: changelog-change

#950 Admission controller example fixes
  examples/admission_controller.rs
  examples/admission_setup.sh
Labels: changelog-fix

#951 docs: clarify that is_crd_stablished does not imply discovery done
  kube-runtime/src/wait.rs
Labels: changelog-exclude

#955 Decouple port forwarding example from HTTP protocol
  examples/Cargo.toml
  examples/pod_portforward_bind.rs
Labels: docs

#959 Make `Config::auth_info` public
  kube-client/src/config/mod.rs
Labels: changelog-add

#960 Fix cargo deny issue
  deny.toml
Labels: changelog-exclude

#956 Constrain Resource trait and Api::namespaced by Scope
  kube-client/src/api/mod.rs
  kube-core/src/dynamic.rs
  kube-core/src/lib.rs
  kube-core/src/object.rs
  kube-core/src/resource.rs
  kube-derive/src/custom_resource.rs
Labels: changelog-change

#963 Document that core `Api` write methods cannot set Status objects
  examples/crd_api.rs
  kube-client/src/api/core_methods.rs
Labels: changelog-exclude

#965 fix duplicate finalizers race condition
  kube-runtime/src/finalizer.rs
Labels: changelog-fix
