Repository kube-rs/kube, pull requests merged in 2022-02, with the labels that each got.

#803 Fix OpenSSF badge
  README.md
Labels: changelog-exclude

#814 add script to propagate written release notes to the changelog
  CHANGELOG.md
  scripts/release-afterdoc.sh
Labels: changelog-exclude

#815 Add conversion for `ObjectRef<K>` to `ObjectReference`
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/object_ref.rs
Labels: runtime, changelog-add

#768 Reload token file at least once a minute
  kube-client/src/client/auth/mod.rs
  kube-client/src/config/incluster_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-change

#821 Fix cargo-deny blocking on duplicate dependencies in examples
  Makefile
  deny.toml
Labels: changelog-exclude

#822 Add a sanity check to keep MSRVs in sync across crates
  README.md
  scripts/msrv.sh
Labels: changelog-exclude

#823 Prefer kubeconfig over in-cluster config
  kube-client/src/config/mod.rs
Labels: bug, config, changelog-change

#825 Update `Client::try_default` documentation
  kube-client/src/client/mod.rs
Labels: changelog-exclude

#811 Entry API
  kube-client/src/api/entry.rs
  kube-client/src/api/mod.rs
Labels: api, changelog-add

#831 [0.69.x] Fix deadlock in token reloading
  kube-client/src/client/auth/mod.rs
Labels: changelog-fix

#834 add hahaha/nais adopters
  ADOPTERS.md
Labels: changelog-exclude

#836 Bump parking_lot to 0.12, but allow dep duplicates
  deny.toml
  kube-runtime/Cargo.toml
Labels: dependencies, changelog-change

#804 Add support for EC private keys
  kube-client/Cargo.toml
  kube-client/src/client/tls.rs
Labels: changelog-add

#838 Bump hyper-openssl and remove parking_lot deny whitelist
  deny.toml
  kube-client/Cargo.toml
Labels: dependencies, changelog-exclude

#842 Let OccupiedEntry::commit take PostParams
  kube-client/src/api/entry.rs
  kube-client/src/api/util/mod.rs
Labels: changelog-change
