Repository kube-rs/kube, pull requests merged in 2022-11, with the labels that each got.

#1062 Add `ExecConfig::drop_env` to filter host evars for auth providers
  kube-client/src/client/auth/mod.rs
  kube-client/src/config/file_config.rs
Labels: config, changelog-add

#1070 Bump tracing dependency to 0.1.36
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-runtime/Cargo.toml
Labels: bug, changelog-fix

#983 Add support for terminal size when executing command inside a container
  examples/Cargo.toml
  examples/pod_shell_crossterm.rs
  kube-client/src/api/mod.rs
  kube-client/src/api/remote_command.rs
Labels: changelog-add

#1081 Bump `chrono`, fix deprecation warnings and a clippy issue
  examples/pod_shell_crossterm.rs
  kube-client/Cargo.toml
  kube-derive/tests/crd_schema_test.rs
Labels: dependencies

#1085 Skip cargo-deny issue on windows deps + rustfmt
  deny.toml
  kube-client/src/client/auth/mod.rs
Labels: changelog-exclude

#1074 add cmd-drop-env to AuthProviderConfig
  kube-client/src/client/auth/mod.rs
Labels: changelog-add
