Repository kube-rs/kube, pull requests merged in 2022-06, with the labels that each got.

#925 fix applier hangs which can happen with many watched objects
  kube-runtime/src/controller/mod.rs
Labels: changelog-fix

#927 [0.73 backport] fix applier hangs which can happen with many watched objects (#925)
  kube-runtime/src/controller/mod.rs
Labels: changelog-fix

#931 Silence false positive `significant_drop_in_scrutinee` for `SplitCase`
  kube-runtime/src/utils/mod.rs
Labels: runtime, changelog-exclude

#932 Applier: Improve reconciler reschedule context to avoid deadlocking on full channel
  kube-derive/src/custom_resource.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/mod.rs
Labels: runtime, changelog-fix

#929 Add support for passing the fieldValidation query parameter on patch
  kube-client/src/api/mod.rs
  kube-core/src/params.rs
Labels: changelog-add

#935 Add conditions::is_job_completed
  examples/job_api.rs
  kube-runtime/src/wait.rs
Labels: changelog-add

#924 Run e2e,integration tests against supported kubernetes versions
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/devcontainer.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  e2e/Cargo.toml
  e2e/Dockerfile
  e2e/README.md
  e2e/boot.rs
  e2e/dapp.rs
  e2e/deployment.yaml
  e2e/job.rs
  justfile
  kube-client/README.md
  kube-derive/src/custom_resource.rs
  kube/src/lib.rs
Labels: changelog-exclude

#939 Fix deserialization issue in AdmissionResponse
  kube-core/src/admission.rs
Labels: changelog-fix
