Repository kube-rs/kube, pull requests merged in 2022-03, with the labels that each got.

#835 Token reloading with RwLock
  kube-client/src/client/auth/mod.rs
Labels: changelog-fix

#847 Fix event publishing for cluster scoped crds
  kube-runtime/src/events.rs
Labels: changelog-fix

#850 Add helper for creating a controller owner_ref on Resource
  deny.toml
  examples/configmapgen_controller.rs
  kube-core/src/resource.rs
Labels: changelog-add

#851 Change ReconcileAction to Action and add associated ctors
  architecture.md
  examples/configmapgen_controller.rs
  examples/secret_syncer.rs
  kube-client/src/api/entry.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/finalizer.rs
Labels: changelog-change

#854 portforward: Improve API and support background task cancelation
  examples/pod_portforward.rs
  examples/pod_portforward_bind.rs
  examples/pod_portforward_hyper_http.rs
  kube-client/src/api/portforward.rs
Labels: changelog-change

#855 Add `ClientBuilder` that lets users add custom middleware without full stack replacement
  kube-client/src/client/builder.rs
  kube-client/src/client/mod.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add

#856 Support top-level enums in CRDs
  kube-derive/src/custom_resource.rs
  kube-derive/tests/crd_enum_test.rs
  kube-derive/tests/ui/enum_fails.stderr
  kube-derive/tests/ui/union_fails.rs
  kube-derive/tests/ui/union_fails.stderr
Labels: changelog-add

#845 Fix schemas containing both properties and additionalProperties
  kube-core/src/schema.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-fix

#857 code coverage message and flags improvements
  .github/codecov.yml
  .github/workflows/clippy.yml
Labels: changelog-exclude

#862 Fix `Portforwarder` doc comment
  kube-client/src/api/portforward.rs
Labels: changelog-exclude

#861 Make remote commands cancellable and remove panics
  examples/pod_attach.rs
  examples/pod_exec.rs
  examples/pod_shell.rs
  kube-client/src/api/remote_command.rs
  kube-client/src/lib.rs
Labels: changelog-change

#863 Change the default TLS to OpenSSL
  .github/workflows/ci.yml
  Makefile
  examples/Cargo.toml
  examples/README.md
  examples/custom_client.rs
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
  kube-client/Cargo.toml
  kube-client/src/lib.rs
Labels: changelog-change

#864 Make dependency pins between sibling crates stricter
  kube-client/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-fix
