Repository kube-rs/kube, pull requests merged in 2022-09, with the labels that each got.

#993 Controller: impl Eq and PartialEq for `Action`
  kube-runtime/src/controller/mod.rs
Labels: changelog-add

#995 Controller: Include the object being reconciled in the `error_policy`
  examples/configmapgen_controller.rs
  examples/crd_api.rs
  examples/secret_syncer.rs
  kube-runtime/src/controller/mod.rs
Labels: changelog-change

#1001 `Config`: New `incluster` and `incluster_dns` constructors
  .devcontainer/devcontainer.json
  kube-client/src/config/incluster_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-change

#999 Add support for CRD `ConversionReview` types
  kube-client/src/lib.rs
  kube-core/src/admission.rs
  kube-core/src/conversion/mod.rs
  kube-core/src/conversion/test_data/simple.json
  kube-core/src/conversion/types.rs
  kube-core/src/lib.rs
  kube-core/src/response.rs
Labels: core, changelog-add

#1008 Upgrade `k8s-openapi` to 0.16
  .github/workflows/ci.yml
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  kube/src/lib.rs
  release.toml
Labels: dependencies, changelog-change

#1019 Runtime: Remove deprecated util `try_flatten_` helpers
  kube-runtime/src/utils/mod.rs
Labels: changelog-remove

#1031 add fieldManager querystring to all operations
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-core/src/subresource.rs
Labels: changelog-fix

#1026 Adds example to `Controller::watches`
  kube-runtime/src/controller/mod.rs
Labels: docs, changelog-add
