Repository kube-rs/kube, pull requests merged in 2022-01, with the labels that each got.

#773 Implement Api fns for arbitrary subresources and approval subresource for Api<CertificateSigningRequest>
  kube-client/src/api/subresource.rs
  kube-client/src/api/util.rs
  kube-client/src/lib.rs
Labels: changelog-add

#766 Use SecretString in AuthInfo to avoid credential leaking
  kube-client/Cargo.toml
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/client/middleware/mod.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/mod.rs
  kube-core/src/util.rs
Labels: changelog-change

#780 Revert "Update dashmap requirement from 4.0.1 to 5.0.0"
  kube-runtime/Cargo.toml
Labels: bug

#779 Support complex enums in CRDs
  CHANGELOG.md
  kube-client/src/api/util.rs
  kube-core/Cargo.toml
  kube-core/src/lib.rs
  kube-core/src/schema.rs
  kube-derive/Cargo.toml
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
  kube/Cargo.toml
Labels: core, changelog-add

#784 Changelog automation and final notes for 0.66.0
  .github/workflows/release.yml
  CHANGELOG.md
Labels: changelog-exclude

#785 runtime: Replace `DashMap` with a locked `AHashMap`
  kube-runtime/Cargo.toml
  kube-runtime/src/reflector/store.rs
Labels: changelog-change

#789 update k8s-openapi for kubernetes 1.23 support
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: dependencies, changelog-change

#786 runtime: Store resources in an `Arc`
  examples/configmapgen_controller.rs
  examples/crd_reflector.rs
  examples/deployment_reflector.rs
  examples/node_reflector.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/finalizer.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
Labels: changelog-change

#792 Propagate Arc through the finalizer reconciler helper
  examples/secret_syncer.rs
  kube-runtime/src/finalizer.rs
Labels: runtime, changelog-change

#788 Add a VS Code devcontainer configuration
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/scurl
  .github/workflows/ci.yml
  .github/workflows/devcontainer.yml
Labels: changelog-add

#795 Use absolute path to Result in derives
  kube-derive/src/custom_resource.rs
Labels: bug, derive, changelog-fix

#797 Add support for user impersonation
  kube-client/src/client/config_ext.rs
  kube-client/src/client/middleware/extra_headers.rs
  kube-client/src/client/middleware/mod.rs
  kube-client/src/client/mod.rs
  kube-client/src/config/mod.rs
Labels: config, client, ergonomics, changelog-add

#798 core: add missing reason to Display on Error::Validation in Request
  kube-core/src/request.rs
Labels: core, errors, changelog-fix

#801 Disable unused default features of chrono crate
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
Labels: changelog-change

#446 Add port forward
  examples/Cargo.toml
  examples/pod_portforward.rs
  examples/pod_portforward_bind.rs
  examples/pod_portforward_hyper_http.rs
  kube-client/src/api/mod.rs
  kube-client/src/api/portforward.rs
  kube-client/src/api/subresource.rs
  kube-core/src/subresource.rs
Labels: client-gold, changelog-add
