Repository kube-rs/kube, pull requests merged in 2022-10, with the labels that each got.

#1041 Pull up clap to 4.0 series
  examples/Cargo.toml
  examples/kubectl.rs
Labels: dependencies, changelog-exclude

#1043 Assorted clippy fixes
  clippy.toml
  examples/crd_derive.rs
  examples/crd_derive_schema.rs
  examples/custom_client_trace.rs
  examples/dynamic_jsonpath.rs
  examples/pod_cp.rs
  kube-client/src/api/mod.rs
  kube-client/src/client/builder.rs
  kube-client/src/config/file_config.rs
  kube-client/src/discovery/apigroup.rs
  kube-core/src/admission.rs
  kube-core/src/object.rs
  kube-core/src/response.rs
  kube-derive/src/custom_resource.rs
Labels: changelog-exclude

#1028 Add support for untagged enums in CRDs
  kube-core/src/schema.rs
  kube-derive/tests/crd_schema_test.rs
Labels: utils, changelog-add

#1045 Revert rename of blacklisted-names -> disallowed-names
  clippy.toml
Labels: bug, changelog-exclude

#1050 Fix compatibility with schemars' preserve_order feature
  kube-core/src/schema.rs
Labels: bug, core, changelog-fix

#1052 Satisfy Clippy
  examples/configmapgen_controller.rs
  kube-client/src/api/portforward.rs
  kube-client/src/config/file_config.rs
  kube-client/src/lib.rs
  kube-core/src/schema.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/finalizer.rs
  kube-runtime/src/reflector/object_ref.rs
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1044 Remove `native-tls` feature
  .github/workflows/ci.yml
  examples/custom_client_tls.rs
  justfile
  kube-client/Cargo.toml
  kube-client/src/client/auth/oauth.rs
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/client/mod.rs
  kube-client/src/client/tls.rs
  kube-client/src/config/mod.rs
  kube-client/src/error.rs
  kube-client/src/lib.rs
  kube/Cargo.toml
Labels: changelog-remove

#1051 Hoist enum values from subschemas
  kube-core/src/schema.rs
  kube-derive/Cargo.toml
  kube-derive/tests/crd_schema_test.rs
Labels: bug, core, changelog-fix

#1061 Add `DynamicObjects::try_parse` for typed object conversion
  kube-core/src/dynamic.rs
Labels: changelog-add
