Repository kube-rs/kube, pull requests merged in 2023-10, with the labels that each got.

#1302 Clippy --fix on runtime pedantics
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_subscribe.rs
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1295 A warning on api version preference being a group concept
  kube-client/src/discovery/apigroup.rs
Labels: changelog-exclude

#1305 Try to fix codecov + tests
  .github/codecov.yml
  .github/workflows/ci.yml
  justfile
  kube-client/src/client/auth/mod.rs
Labels: changelog-exclude

#1304 Document `Controller::reconcile_on` and remove `Err` input requirement
  kube-runtime/src/controller/mod.rs
Labels: changelog-fix, unstable

#1308 Bump `base64` to `0.21`
  kube-client/Cargo.toml
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/upgrade.rs
  kube-client/src/config/file_config.rs
Labels: dependencies, changelog-change

#1307 Upgrade `darling` and `syn` and rename `#[kube(struct)]`
  examples/crd_derive.rs
  kube-derive/Cargo.toml
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
Labels: dependencies, changelog-change

#1326 Fix a cargo deny issue on missing tree
  deny.toml
Labels: changelog-exclude

#1320 Fixed KUBERNETES_EXEC_INFO environment variable passed to auth plugins
  kube-client/src/client/auth/mod.rs
Labels: changelog-fix

#1324 Fix `Controller`: pending messages are stuck in the `scheduled` map
  kube-runtime/src/controller/runner.rs
  kube-runtime/src/scheduler.rs
Labels: changelog-fix

#1314 Set a default write timeout
  kube-client/src/config/mod.rs
Labels: changelog-fix

#1311 Feature-flagged support for `socks5` proxy in `Client`
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/config/mod.rs
  kube/Cargo.toml
Labels: changelog-add

#1330 Add example for raw API Server requests
  examples/Cargo.toml
  examples/request_raw.rs
Labels: changelog-add
