Repository kube-rs/kube, pull requests merged in 2023-01, with the labels that each got.

#1113 Remove deprecated `Config::timeout`
  kube-client/src/client/builder.rs
  kube-client/src/config/mod.rs
Labels: changelog-remove

#1116 Bump `k8s-openapi@0.17.0` and MK8SV
  .github/workflows/ci.yml
  README.md
  deny.toml
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-client/src/api/util/mod.rs
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/lib.rs
  kube/Cargo.toml
  release.toml
Labels: changelog-change

#1119 Add better keywords/categories to `Cargo.toml`
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-exclude

#1120 Config: make cluster/users/clusters optional
  kube-client/src/config/file_config.rs
Labels: changelog-fix

#1123 Client: expose `default_namespace()`
  kube-client/src/api/mod.rs
  kube-client/src/client/mod.rs
Labels: client, changelog-add
