Repository kube-rs/kube, pull requests merged in 2023-09, with the labels that each got.

#1277 allow configuring controller's concurrency
  examples/configmapgen_controller.rs
  kube-runtime/src/controller/future_hash_map.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/controller/runner.rs
  kube-runtime/src/scheduler.rs
Labels: changelog-add

#1290 fix kube-runtime comment typo
  kube-runtime/src/controller/runner.rs
Labels: changelog-exclude

#1287 Revamp event and log examples to allow more parameters
  examples/README.md
  examples/event_watcher.rs
  examples/kubectl.rs
  examples/log_stream.rs
Labels: changelog-exclude

#1261 Change default TLS stack to `rustls-tls`
  .github/workflows/ci.yml
  README.md
  examples/Cargo.toml
  examples/README.md
  examples/custom_client.rs
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
  kube-client/src/client/auth/oauth.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/builder.rs
  kube-client/src/error.rs
  kube/Cargo.toml
Labels: changelog-change

#1291 Bump k8s-openapi to 0.20.0
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  release.toml
Labels: changelog-change

#1292 Change explicit `v1_28` feature to use `latest` feature alias
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  release.toml
Labels: changelog-exclude
