Repository kube-rs/kube, pull requests merged in 2023-04, with the labels that each got.

#1171 Make `VersionMatch` follow upstream + configure list semantics in `watcher::Config`
  deny.toml
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-runtime/src/watcher.rs
Labels: changelog-change

#911 Add `predicates` to allow filtering `watcher` streams
  examples/Cargo.toml
  examples/node_reflector.rs
  justfile
  kube-runtime/Cargo.toml
  kube-runtime/src/lib.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/predicate.rs
  kube-runtime/src/utils/watch_ext.rs
  kube/Cargo.toml
Labels: changelog-add, unstable

#1173 Add `Controller::owns_stream`
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
Labels: changelog-add, unstable

#1182 Bump rustls,hyper-rustls - for #1181
  deny.toml
  kube-client/Cargo.toml
  kube-client/src/client/tls.rs
Labels: dependencies, changelog-exclude

#1183 Run `rustls` CI against IP cluster address
  .github/workflows/ci.yml
Labels: changelog-fix

#1185 Fix: tower buffer's worker closed unexpectedly
  examples/Cargo.toml
  kube-client/Cargo.toml
Labels: dependencies, changelog-fix

#1184 Avoid special `Config::incluster` behavior for `rustls`
  README.md
  kube-client/src/config/mod.rs
  kube-runtime/src/controller/mod.rs
Labels: changelog-fix

#1079 kube-derive: Disable `option_nullable` for CRD generation
  kube-derive/src/custom_resource.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-change

#1187 Add `Controller::for_stream` + `Controller::watches_stream`
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/predicate.rs
  kube-runtime/src/utils/watch_ext.rs
  kube-runtime/src/watcher.rs
Labels: changelog-add, unstable

#1188 Bump `serde_yaml` to 0.9
  examples/Cargo.toml
  examples/crd_derive.rs
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-derive/src/lib.rs
Labels: dependencies, changelog-change

#1190 Bump `k8s-openapi` to 0.18.0
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/events.rs
  kube/Cargo.toml
Labels: dependencies, changelog-change

#1193 Fix `WatchParams` bookmarks for `watch_metadata`
  kube-core/src/admission.rs
  kube-core/src/params.rs
  kube-core/src/request.rs
Labels: changelog-fix

#1199 Fix `ObjectList` not deserializing `items: null`
  kube-core/src/object.rs
Labels: changelog-fix

#1201 Revert "kube-derive: Disable `option_nullable` for CRD generation"
  kube-derive/src/custom_resource.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-fix

#1204 runtime::watcher: only set rv if semantic is any
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1206 `watcher::Config`: Derive `Clone` + `Debug` + `PartialEq`
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1212 Swap `validator` for `garde`
  examples/Cargo.toml
  examples/crd_api.rs
  kube-derive/Cargo.toml
  kube-derive/src/lib.rs
  kube/Cargo.toml
  kube/src/lib.rs
Labels: changelog-fix

#1163 Add Controller::reconcile_on
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
Labels: changelog-add, unstable
