Repository kube-rs/kube, pull requests merged in 2023-03, with the labels that each got.

#1155 Bypass nightly ICE in docs build
  kube/src/lib.rs
Labels: changelog-fix

#1152 Genericize `PartialObjectMeta` over the underlying `Resource`
  justfile
  kube-client/src/api/core_methods.rs
  kube-client/src/api/mod.rs
  kube-client/src/lib.rs
  kube-core/src/lib.rs
  kube-core/src/metadata.rs
  kube-runtime/src/lib.rs
  kube-runtime/src/watcher.rs
Labels: runtime, core, changelog-change

#1158 Documentation cleanup around `Api` core_methods and `dynamic_watcher`
  examples/dynamic_watcher.rs
  kube-client/src/api/core_methods.rs
  kube-core/src/metadata.rs
  kube-runtime/src/watcher.rs
Labels: docs, changelog-exclude

#1162 Split ListParams and WatchParams
  examples/configmapgen_controller.rs
  examples/crd_derive_schema.rs
  examples/crd_reflector.rs
  examples/dynamic_watcher.rs
  examples/event_watcher.rs
  examples/kubectl.rs
  examples/multi_watcher.rs
  examples/node_reflector.rs
  examples/node_watcher.rs
  examples/pod_attach.rs
  examples/pod_cp.rs
  examples/pod_evict.rs
  examples/pod_exec.rs
  examples/pod_reflector.rs
  examples/pod_shell.rs
  examples/pod_watcher.rs
  examples/secret_reflector.rs
  examples/secret_syncer.rs
  kube-client/src/api/core_methods.rs
  kube-client/src/api/mod.rs
  kube-client/src/lib.rs
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/watcher.rs
  kube/src/lib.rs
Labels: changelog-change

#1166 Minor docs improvements/fixes, deny fix + macros dep fix
  deny.toml
  kube-client/Cargo.toml
  kube-client/src/lib.rs
  kube-core/src/params.rs
  kube-derive/src/lib.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/events.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/watcher.rs
Labels: changelog-exclude
