Repository kube-rs/kube, pull requests merged in 2023-02, with the labels that each got.

#1134 Add better logging for watcher errors
  examples/crd_derive_multi.rs
  examples/pod_shell_crossterm.rs
  kube-client/src/config/file_loader.rs
  kube-client/src/lib.rs
  kube-core/src/crd.rs
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1137 Add support for metadata API
  kube-client/src/api/core_methods.rs
  kube-client/src/lib.rs
  kube-core/src/metadata.rs
  kube-core/src/request.rs
Labels: api, core, changelog-add

#1138 cargo deny fix build + add `.mailmap`
  .mailmap
  deny.toml
  justfile
Labels: dependencies, changelog-exclude

#1141 Integration tests; add `#[ignore = "msg"]` messages
  kube-client/src/api/entry.rs
  kube-client/src/api/util/mod.rs
  kube-client/src/lib.rs
  kube-runtime/src/events.rs
  kube-runtime/src/utils/mod.rs
  kube/src/lib.rs
  scripts/release-post.sh
  scripts/release-pre.sh
Labels: changelog-exclude

#1142 kubeconfig: deserialize null vectors as default
  kube-client/src/config/file_config.rs
Labels: changelog-fix

#1143 Unit/Integration CI test cleanup
  .github/workflows/ci.yml
  .github/workflows/rustfmt.yml
  CONTRIBUTING.md
  justfile
  kube-client/src/api/remote_command.rs
  kube-client/src/config/file_config.rs
  kube-core/src/admission.rs
  kube-derive/Cargo.toml
  kube-derive/src/lib.rs
  release.toml
  scripts/release-post.sh
  scripts/release-pre.sh
Labels: automation, changelog-exclude

#1146 Bump Rust MSRV to 1.63.0
  .devcontainer/Dockerfile
  README.md
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-change

#1131 Runtime: Add `WatchStreamExt::subscribe`
  kube-runtime/Cargo.toml
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_subscribe.rs
  kube-runtime/src/utils/watch_ext.rs
  kube/Cargo.toml
Labels: changelog-add

#1145 Introduce support for persistent metadata watches
  examples/dynamic_watcher.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/lib.rs
  kube-runtime/src/watcher.rs
Labels: changelog-add
