Repository kube-rs/kube, pull requests merged in 2023-11, with the labels that each got.

#1334 Fix `connector` shadowing to fix no-tls build
  .github/workflows/ci.yml
  kube-client/src/client/builder.rs
Labels: changelog-exclude

#1341 Update kube-client's rustls dependency to `0.21.4`
  kube-client/Cargo.toml
Labels: changelog-exclude

#1342 Add support for `LogParams::since_time`
  examples/log_stream.rs
  kube-core/src/subresource.rs
Labels: changelog-add

#1353 Bump MSRV from 1.64 to 1.65
  .devcontainer/Dockerfile
  README.md
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-change

#1345 Switch from `jsonpath_lib` to `jsonpath-rust`
  examples/Cargo.toml
  examples/dynamic_jsonpath.rs
  kube-client/Cargo.toml
  kube-client/src/client/auth/mod.rs
Labels: changelog-change

#1331 Provide cluster info to exec plugins
  kube-client/src/client/auth/mod.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/file_loader.rs
  kube-client/src/config/mod.rs
Labels: changelog-add
