Repository kube-rs/kube, pull requests merged in 2023-08, with the labels that each got.

#1271 Upgrade `k8s-openapi` to `0.19.0` for `v1_27` support
  .github/workflows/ci.yml
  README.md
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  release.toml
Labels: dependencies, changelog-change

#1272 Bump `pem` to 3
  kube-client/Cargo.toml
  kube-client/src/config/mod.rs
Labels: dependencies, changelog-exclude

#1265 add `controller::Config` and debounce period to scheduler
  kube-client/src/client/mod.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/controller/runner.rs
  kube-runtime/src/lib.rs
  kube-runtime/src/scheduler.rs
Labels: changelog-add

#1283 Fix/ignore cargo-deny report on dual use of socket2
  deny.toml
Labels: changelog-exclude

#1255 adds watch-list implementation without breaking changes
  examples/Cargo.toml
  examples/namespace_reflector.rs
  justfile
  kube-client/src/client/tls.rs
  kube-core/src/params.rs
  kube-core/src/request.rs
  kube-core/src/watch.rs
  kube-runtime/src/watcher.rs
Labels: changelog-add

#1281 `core`: omit invalid resource version parameters when doing paged requests
  kube-core/src/params.rs
  kube-core/src/request.rs
Labels: changelog-fix

#1284 Fixup watcher docs, and watchlist doc examples
  examples/Cargo.toml
  examples/README.md
  examples/event_watcher.rs
  examples/namespace_reflector.rs
  examples/node_watcher.rs
  examples/pod_watcher.rs
  kube-core/src/params.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_subscribe.rs
  kube-runtime/src/watcher.rs
Labels: docs, changelog-exclude

#1288 Fix clippy isuses on rust 1.72
  Cargo.toml
  kube-client/src/client/auth/oidc.rs
  kube/src/mock_tests.rs
Labels: changelog-exclude
