Repository kube-rs/kube, pull requests merged in 2023-05, with the labels that each got.

#1214 Introduce `GetParams` support
  kube-client/src/api/core_methods.rs
  kube-client/src/api/mod.rs
  kube-core/src/params.rs
  kube-core/src/request.rs
Labels: changelog-change

#1202 Hack windows tests to use `rustls` to avoid openssl breakage
  .github/codecov.yml
  .github/workflows/ci.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/rustfmt.yml
  kube-client/Cargo.toml
Labels: automation, changelog-exclude

#1215 fix: `#[kube(crates(serde = "some_crate::serde"))]` was not working
  kube-derive/src/custom_resource.rs
Labels: changelog-fix

#1216 Fix ```apply``` Action within Example ```kubectl```
  examples/kubectl.rs
Labels: changelog-exclude
