Repository kube-rs/kube, pull requests merged in 2023-07, with the labels that each got.

#1238 Fixes new clippy lints
  kube-client/src/api/portforward.rs
  kube-client/src/client/auth/oidc.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_subscribe.rs
  kube-runtime/src/wait.rs
Labels: changelog-exclude

#1237 Derive `PartialEq` on `core` params structs
  kube-core/src/params.rs
Labels: changelog-add

#1235 Change `Api::log_stream` to return `AsyncBufRead`
  examples/log_stream.rs
  kube-client/src/api/subresource.rs
  kube-client/src/client/mod.rs
  kube-client/src/lib.rs
Labels: changelog-change

#1240 Make `Controller::owns` use `metadata_watcher` internally
  kube-runtime/src/controller/mod.rs
Labels: changelog-fix

#1246 Add `WatchStreamExt::modify()` to modify events
  examples/pod_reflector.rs
  kube-runtime/src/utils/event_modify.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-add

#1249 Add default pagination to `watcher`
  examples/pod_paged.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/controller/runner.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/utils/delayed_init.rs
  kube-runtime/src/utils/event_modify.rs
  kube-runtime/src/watcher.rs
  kube/Cargo.toml
  kube/src/lib.rs
  kube/src/mock_tests.rs
Labels: changelog-add

#1250 Watcher pagination handle empty string continue token
  kube-runtime/src/watcher.rs
  kube/src/mock_tests.rs
Labels: changelog-exclude

#1252 Add `WatchStreamExt::reflect` to allow chaining on a reflector
  examples/crd_reflector.rs
  examples/node_reflector.rs
  examples/pod_reflector.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/reflect.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-add

#1259 return `NoResourceVersion` error if resource version is empty
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1260 Update the scheduler message when preponing
  kube-runtime/Cargo.toml
  kube-runtime/src/scheduler.rs
Labels: changelog-fix

#1207 Swap `dirs-next` dependency to cargo-team maintained `home` crate
  kube-client/Cargo.toml
  kube-client/src/config/file_config.rs
Labels: changelog-change

#1258 dynamic_watcher example: show how to use dynamic type information at loop level
  examples/dynamic_watcher.rs
Labels: changelog-exclude

#1153 Implement ephemeral containers subresource
  kube-client/src/api/mod.rs
  kube-client/src/api/subresource.rs
  kube-client/src/lib.rs
Labels: changelog-add
