Repository kube-rs/kube, pull requests merged in 2023-06, with the labels that each got.

#1221 Add `predicates::resource_version`
  kube-client/src/api/util/mod.rs
  kube-client/src/lib.rs
  kube-runtime/src/utils/predicate.rs
  kube-runtime/src/utils/watch_ext.rs
  kube/src/lib.rs
Labels: runtime, changelog-add

#1224 add `Duration` to `kube-core`
  kube-core/src/duration.rs
  kube-core/src/lib.rs
Labels: changelog-add

#1230 docs: change phrasing on reflector mod
  kube-runtime/src/reflector/mod.rs
Labels: changelog-exclude

#1228 Add `Predicate` trait to allow combination + fallbacks
  examples/node_reflector.rs
  examples/pod_reflector.rs
  kube-core/src/request.rs
  kube-runtime/src/lib.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/predicate.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-add, unstable

#1233 Bump MSRV from 1.63 to 1.64
  .devcontainer/Dockerfile
  README.md
  deny.toml
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-change

#1229 Added refreshing OIDC ID token as an optional feature
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/mod.rs
  kube/Cargo.toml
Labels: changelog-add

#1232 Add `WatchStreamExt::default_backoff` shorthand
  examples/node_watcher.rs
  examples/pod_watcher.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/utils/watch_ext.rs
  kube-runtime/src/watcher.rs
Labels: changelog-add
