Repository kube-rs/kube, pull requests merged in 2024-11, with the labels that each got.

#1625 Fix errors and warnings for the `.reflect_shared()` example
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-exclude

#1626 Warn when trying to use an unsupported proxy protocol
  kube-client/src/client/builder.rs
  kube-client/src/error.rs
Labels: changelog-fix

#1636 Temporarily ignore rustsec warning for unmaintained instant
  deny.toml
Labels: changelog-exclude

#1631 add support for CRD annotations and labels in kube-derive
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add

#1628 Feature: Add config setting to disable gzip compression #1627
  kube-client/Cargo.toml
  kube-client/src/client/builder.rs
  kube-client/src/config/file_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-add

#1646 Fix inconsistencies in rustfmt editions on CI and local
  .github/workflows/lint.yml
  .github/workflows/rustfmt.yml
  deny.toml
  rustfmt.toml
Labels: changelog-exclude

#1644 feat: Add storage and served argument to derive macro
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add

#1647 Update kubectl example to include optional context argument
  examples/kubectl.rs
Labels: changelog-exclude
