Repository kube-rs/kube, pull requests merged in 2024-05, with the labels that each got.

#1470 Remove abandoned `StreamSubscribe` implementation
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/stream_subscribe.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-remove, unstable

#1484 Remove invalid `uniqueItems` property from CRDs when Sets are used
  kube-core/src/schema.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-fix

#1483 feat(runtime): support for owned shared streams
  examples/shared_stream_controllers.rs
  kube-runtime/src/controller/mod.rs
Labels: changelog-add, unstable

#1485 Upgrade `k8s-openapi` to 0.22 and bump MK8SV to 1.25
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  Cargo.toml
  README.md
  e2e/Cargo.toml
  justfile
Labels: changelog-change

#1489 Fix potentially panicing unchecked duration adds in runtime
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/scheduler.rs
Labels: changelog-fix

#1492 ObjectList now accepts null metadata like upstream k8s does
  .github/workflows/ci.yml
  kube-core/src/object.rs
Labels: changelog-fix

#1496 Added support for HTTP proxy with hyper-proxy2
  kube-client/Cargo.toml
  kube-client/src/client/builder.rs
  kube/Cargo.toml
Labels: changelog-add

#1494 Reduce buffering between watcher and Store
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/reflector/dispatcher.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/utils/event_flatten.rs
  kube-runtime/src/utils/event_modify.rs
  kube-runtime/src/utils/reflect.rs
  kube-runtime/src/watcher.rs
Labels: changelog-change

#1501 rename http_proxy feature to http-proxy and add it to the umbrella crate
  kube-client/Cargo.toml
  kube/Cargo.toml
Labels: changelog-fix

#1502 add feature propagation to hyper-proxy2 dependency
  kube-client/Cargo.toml
  kube-client/src/client/builder.rs
Labels: changelog-fix

#1499 Rename new watcher Event names and remove one that cannot happen
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/reflector/dispatcher.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/utils/event_flatten.rs
  kube-runtime/src/utils/event_modify.rs
  kube-runtime/src/utils/reflect.rs
  kube-runtime/src/watcher.rs
Labels: changelog-change
