Repository kube-rs/kube, pull requests merged in 2024-09, with the labels that each got.

#1566 Fix deny build (skip duplicate rule on miniz_oxide)
  deny.toml
Labels: changelog-exclude

#1567 fix new doc clippy lint
  kube-client/src/config/file_config.rs
  kube-client/src/config/mod.rs
Labels: changelog-exclude

#1552 Provide example on predicate usage for shared streams
  examples/shared_stream_controllers.rs
Labels: docs

#1571 Add a missing dot in README.md
  README.md
Labels: changelog-exclude

#1565 Add `Resource` derive macro
  examples/Cargo.toml
  examples/README.md
  examples/cert_check.rs
  examples/errorbounded_configmap_watcher.rs
  kube-derive/src/lib.rs
  kube-derive/src/resource.rs
  kube-derive/tests/resource.rs
  kube/src/lib.rs
Labels: changelog-add

#1573 Doc tweaks and 2 missing impls pre release
  examples/README.md
  examples/cert_check.rs
  kube-client/src/client/client_ext.rs
  kube-client/src/client/mod.rs
  kube-client/src/config/mod.rs
  kube-core/src/lib.rs
  kube-derive/src/lib.rs
  kube/src/lib.rs
Labels: changelog-exclude

#1575 Update hyper-rustls minimum version
  Cargo.toml
Labels: changelog-fix

#1577 Ensure `watch_object` handles objects removed before init
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1585 replace derivative dependency with educe
  Cargo.toml
  deny.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/lib.rs
  kube-runtime/src/reflector/dispatcher.rs
  kube-runtime/src/reflector/object_ref.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/scheduler.rs
  kube-runtime/src/utils/delayed_init.rs
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1587 remove using HTTP PROXY from environment variable
  kube-client/src/config/file_loader.rs
Labels: changelog-change

#1588 Bump `secrecy` to 0.10
  Cargo.toml
  kube-client/Cargo.toml
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/config/file_config.rs
Labels: dependencies, changelog-change

#1589 Upgrades Tower to 0.5.1
  Cargo.toml
  examples/custom_client.rs
  examples/custom_client_trace.rs
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/client/mod.rs
Labels: dependencies, changelog-change

#1323 rustls: optionally use WebPKI roots to avoid panicking on Android & iOS
  deny.toml
  kube-client/Cargo.toml
  kube-client/src/client/auth/oauth.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/tls.rs
  kube/Cargo.toml
Labels: changelog-add
