Repository kube-rs/kube, pull requests merged in 2024-06, with the labels that each got.

#1509 Update `tokio-tungstenite` to 0.23
  Cargo.toml
Labels: dependencies, changelog-change

#1504 Align `watcher::Event` init/page variants
  Cargo.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/reflector/dispatcher.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/utils/event_flatten.rs
  kube-runtime/src/utils/event_modify.rs
  kube-runtime/src/utils/predicate.rs
  kube-runtime/src/utils/reflect.rs
  kube-runtime/src/utils/watch_ext.rs
  kube-runtime/src/watcher.rs
Labels: changelog-change

#1510 runtime: document scope footgun in `watch_object`
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1507 Update json-patch to 2.0.0
  Cargo.toml
  examples/Cargo.toml
  examples/admission_controller.rs
  kube-core/Cargo.toml
  kube-core/src/admission.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/finalizer.rs
Labels: dependencies, changelog-change

#1514 refactor: use upstream http_body_util::BodyDataStream
  Cargo.toml
  kube-client/src/client/body.rs
Labels: changelog-exclude

#1515 Upgrade garde to 0.19 for examples
  examples/Cargo.toml
  examples/crd_api.rs
Labels: dependencies, changelog-exclude

#1511 Implement client native object reference fetching
  kube-client/src/client/client_ext.rs
  kube-client/src/error.rs
  kube-core/src/gvk.rs
Labels: changelog-add, unstable

#1516 Fix license deny failures for Unicode-3.0 license
  deny.toml
Labels: changelog-exclude

#1523 add option to provide headers to send as client
  kube-client/src/client/config_ext.rs
  kube-client/src/config/mod.rs
Labels: changelog-add

#1525 Fix watcher not fully paginating on Init
  kube-runtime/src/watcher.rs
  kube/src/mock_tests.rs
Labels: changelog-fix

#1518 runtime: remove deprecated default_backoff
  kube-runtime/src/watcher.rs
Labels: changelog-remove

#1526 docs: point out that Kubeconfig client_key structs are base64 encoded
  kube-client/src/config/file_config.rs
Labels: docs, changelog-exclude
