Repository kube-rs/kube, pull requests merged in 2024-03, with the labels that each got.

#1393 Ease the bound for `reflector` to only request identifying metadata
  kube-core/src/lib.rs
  kube-core/src/resource.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/object_ref.rs
  kube-runtime/src/reflector/store.rs
Labels: changelog-change

#1417 More conservative clippy fixes
  kube-client/src/api/subresource.rs
  kube-runtime/src/events.rs
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1375 client_ext for `Client::get` and `Client::list`
  examples/Cargo.toml
  examples/node_watcher.rs
  kube-client/Cargo.toml
  kube-client/src/client/client_ext.rs
  kube-client/src/client/mod.rs
  kube-client/src/config/mod.rs
  kube-client/src/discovery/apigroup.rs
  kube-client/src/error.rs
  kube-client/src/lib.rs
  kube/Cargo.toml
Labels: changelog-add, unstable

#1429 upgrade `jsonpath-rust` to 0.5.0
  examples/Cargo.toml
  examples/dynamic_jsonpath.rs
  kube-client/Cargo.toml
  kube-client/src/client/auth/mod.rs
Labels: dependencies, changelog-change

#1432 `Kubeconfig` allow `certificate_authority_data` not present in `ExecAuthCluster`
  kube-client/src/config/file_config.rs
Labels: changelog-fix

#1433 fix: check err on `Client::request_stream`
  kube-client/src/client/mod.rs
Labels: changelog-fix

#1428 feat: direct node access logs/portforward/exec/attach
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  examples/Cargo.toml
  examples/pod_log_kubelet_debug.rs
  justfile
  kube-client/Cargo.toml
  kube-client/src/api/subresource.rs
  kube-client/src/client/builder.rs
  kube-client/src/client/kubelet_debug.rs
  kube-client/src/client/mod.rs
  kube-client/src/lib.rs
  kube-core/Cargo.toml
  kube-core/src/kubelet_debug.rs
  kube-core/src/lib.rs
  kube-core/src/subresource.rs
  kube/Cargo.toml
Labels: changelog-add

#1435 Workspacify deps
  Cargo.toml
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
Labels: changelog-exclude

#1436 clippy suggestions and warning removal
  examples/secret_reflector.rs
  kube-client/Cargo.toml
  kube-client/src/api/entry.rs
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/mod.rs
  kube-client/src/lib.rs
  kube-runtime/src/events.rs
  kube-runtime/src/reflector/object_ref.rs
  kube/src/mock_tests.rs
Labels: changelog-exclude

#1438 update to hyper 1
  .devcontainer/Dockerfile
  Cargo.toml
  README.md
  examples/Cargo.toml
  examples/custom_client.rs
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
  examples/pod_portforward_hyper_http.rs
  examples/request_raw.rs
  kube-client/Cargo.toml
  kube-client/src/api/mod.rs
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/auth/oauth.rs
  kube-client/src/client/auth/oidc.rs
  kube-client/src/client/body.rs
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/client/middleware/mod.rs
  kube-client/src/client/mod.rs
  kube-client/src/client/tls.rs
  kube-client/src/client/upgrade.rs
  kube-client/src/lib.rs
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
  kube/Cargo.toml
  kube/src/mock_tests.rs
Labels: changelog-change

#1437 Factor out workspace props
  .github/workflows/ci.yml
  Cargo.toml
  e2e/Cargo.toml
  examples/Cargo.toml
  justfile
  kube-client/Cargo.toml
  kube-client/src/lib.rs
  kube-core/Cargo.toml
  kube-core/src/lib.rs
  kube-derive/Cargo.toml
  kube-derive/src/lib.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/lib.rs
  kube/Cargo.toml
  kube/src/lib.rs
Labels: changelog-exclude

#1440 Fix minor new lints and better info on pod reflector memory usage
  kube-client/src/client/config_ext.rs
  kube-client/src/client/middleware/mod.rs
  kube-client/src/client/mod.rs
  kube-client/src/config/mod.rs
  kube-runtime/src/reflector/mod.rs
Labels: changelog-exclude

#1442 disable unused futures feature
  Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
Labels: changelog-fix

#1444 Expose `Body::empty` for easier tests
  kube-client/src/client/body.rs
Labels: changelog-fix

#1448 replace chrono feature clock with now
  Cargo.toml
  kube-core/Cargo.toml
Labels: changelog-fix

#1452 implement http body trait method
  kube-client/src/client/body.rs
Labels: changelog-fix

#1453 refactor converting body to data stream
  kube-client/src/client/body.rs
  kube-client/src/client/mod.rs
Labels: changelog-exclude

#1450 Fix examples for custom clients not authenticating
  examples/custom_client_tls.rs
  examples/custom_client_trace.rs
Labels: changelog-fix
