Repository kube-rs/kube, pull requests merged in 2024-12, with the labels that each got.

#1655 feat(runtime): Add series implementation for event recorder
  Cargo.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/events.rs
Labels: changelog-change

#1665 chore(deps): Update Rust crate hostname to 0.4
  Cargo.toml
Labels: changelog-exclude

#1649 Implement `derive(CELSchema)` macro for generating cel validation on CRDs
  Cargo.toml
  examples/crd_derive_schema.rs
  kube-core/src/cel.rs
  kube-core/src/lib.rs
  kube-derive/Cargo.toml
  kube-derive/src/cel_schema.rs
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
  kube/src/lib.rs
Labels: changelog-add, cel

#1671 Bump `k8s-openapi` for Kubernetes `v1_32` support and MSRV
  .devcontainer/Dockerfile
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  Cargo.toml
  README.md
  e2e/Cargo.toml
  justfile
Labels: changelog-change
