Repository kube-rs/kube, pull requests merged in 2024-04, with the labels that each got.

#1455 refactor: remove BodyDataStream
  kube-client/Cargo.toml
  kube-client/src/client/body.rs
  kube-client/src/client/mod.rs
Labels: changelog-exclude

#1457 update to rustls 0.23
  Cargo.toml
  kube-client/Cargo.toml
Labels: changelog-change

#1445 Add proxy `Body::collect_bytes` for easier unit tests
  kube-client/src/client/body.rs
Labels: changelog-add

#1458 Set a compatible minimum `chrono` version
  Cargo.toml
Labels: changelog-fix

#1462 refactor client body
  kube-client/src/client/body.rs
Labels: changelog-exclude

#1464 refactor client body
  kube-client/src/client/body.rs
Labels: changelog-exclude

#1466 tests: upgraded tarpaulin and added derive macro coverage
  .github/workflows/coverage.yml
  deny.toml
  justfile
  kube-derive/Cargo.toml
  kube-derive/src/custom_resource.rs
  tarpaulin.toml
Labels: changelog-exclude

#1468 tarpaulin from release
  .github/workflows/coverage.yml
Labels: automation, changelog-exclude

#1449 Add shared stream interfaces
  Cargo.toml
  examples/Cargo.toml
  examples/shared_stream_controllers.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/reflector/dispatcher.rs
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-add

#1471 Fix minor broken doc links and add missing feature flag
  kube-runtime/src/reflector/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/scheduler.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: changelog-exclude

#1479 Minor readme fixes
  README.md
Labels: changelog-exclude

#1475 Allow to create non-controller owner reference for resource
  kube-core/src/resource.rs
Labels: changelog-add
