Repository kube-rs/kube, pull requests merged in 2024-10, with the labels that each got.

#1520 runtime: rename references from Flatten to Decode
  README.md
  deny.toml
  kube-runtime/src/utils/event_decode.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/watch_ext.rs
  kube-runtime/src/watcher.rs
Labels: changelog-change

#1595 change auth behavior to match upstream on unknown/empty user - use null auth
  kube-client/src/config/file_loader.rs
  kube-client/src/config/mod.rs
Labels: changelog-fix

#1596 clippy fixes
  kube-client/src/api/core_methods.rs
  kube-core/src/duration.rs
  kube-core/src/object.rs
  kube-runtime/src/controller/mod.rs
  kube-runtime/src/reflector/store.rs
  kube-runtime/src/scheduler.rs
  kube-runtime/src/utils/delayed_init.rs
Labels: changelog-exclude

#1578 Stabilise runtime predicates
  kube-runtime/Cargo.toml
  kube-runtime/src/lib.rs
  kube-runtime/src/utils/mod.rs
  kube-runtime/src/utils/watch_ext.rs
Labels: runtime, changelog-add

#1598 Add ObjectRef::from as alias for ::from_obj
  kube-runtime/src/reflector/object_ref.rs
Labels: runtime, ergonomics, changelog-add

#1599 upgrade to hashbrown 0.15.0
  Cargo.toml
  deny.toml
  kube-runtime/src/scheduler.rs
Labels: dependencies, changelog-change

#1600 update jsonptr + json-patch
  Cargo.toml
  examples/admission_controller.rs
  kube-core/src/admission.rs
  kube-runtime/src/finalizer.rs
Labels: dependencies, changelog-change

#1603 fix(kube-runtime): setup backoff with builder pattern
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1605 Feature: Allow to pass selectableFields for CRD definition
  examples/crd_derive.rs
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add

#1608 allow null user in kubeconfig's context
  kube-client/src/config/file_config.rs
  kube-client/src/config/file_loader.rs
Labels: changelog-fix

#1610 Gauge SelectableField by k8s 1.30 version
  kube-derive/src/custom_resource.rs
Labels: changelog-fix

#1612 Add a compile_error if setting selectable fields on K8s < 1.30
  kube-derive/src/custom_resource.rs
Labels: changelog-fix

#1617 conditionally install `aws-lc-rs`
  kube-client/src/client/auth/oidc.rs
Labels: changelog-fix

#1616 Change event watcher example to retry the connection
  examples/event_watcher.rs
Labels: changelog-exclude

#1619 Fix custom client tls ex
  .github/workflows/ci.yml
  examples/custom_client_tls.rs
Labels: docs, changelog-exclude

#1620 Move away from deprecated actions-rs
  .github/workflows/audit.yml
  .github/workflows/ci.yml
  .github/workflows/clippy.yml
  .github/workflows/lint.yml
  .github/workflows/rustfmt.yml
  justfile
Labels: changelog-exclude
