Repository kube-rs/kube, pull requests merged in 2024-07, with the labels that each got.

#1527 Add prelude for blanket and extension traits across sub-crates
  kube-client/src/client/client_ext.rs
  kube-runtime/src/utils/watch_ext.rs
  kube/src/lib.rs
Labels: changelog-add

#1541 Prevent empty string object name requests from being sent to the apiserver
  kube-core/src/request.rs
Labels: changelog-fix

#1539 Label selector support
  kube-core/src/labels.rs
  kube-core/src/lib.rs
  kube-core/src/params.rs
  kube-runtime/src/watcher.rs
  kube/src/lib.rs
Labels: changelog-add

#1542 Doc cleanup for label selectors
  kube-core/src/labels.rs
  kube-core/src/params.rs
  kube-derive/src/lib.rs
Labels: changelog-exclude

#1543 Unused warnings in body.rs and admission example
  examples/admission_controller.rs
  kube-client/src/client/body.rs
Labels: changelog-exclude

#1546 Fix docs mentioning Event::Restarted
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1547 Missed doc updates
  README.md
  kube/src/lib.rs
Labels: changelog-exclude

#1549 add missing feature gate on ConfigExt for no-features build
  kube/src/lib.rs
Labels: changelog-fix

#1550 Add missing test instruction for no-features build
  .github/workflows/ci.yml
Labels: changelog-exclude

#1551 Make implicitly dependent feature explicitly depend on each other
  .github/workflows/features.yml
  justfile
  kube/Cargo.toml
Labels: changelog-change
