Repository kube-rs/kube, pull requests merged in 2025-02, with the labels that each got.

#1685 Fix dumbass pendantic clippy.
  kube-runtime/src/controller/runner.rs
  kube-runtime/src/events.rs
Labels: changelog-exclude

#1686 Bump `rand` to 0.9
  Cargo.toml
  deny.toml
  kube-runtime/src/reflector/mod.rs
Labels: dependencies

#1690 use rustls-pki-types pem api
  Cargo.toml
  kube-client/Cargo.toml
  kube-client/src/client/tls.rs
Labels: dependencies, changelog-exclude

#1656 feat: Add typed scale argument to derive macro
  examples/crd_api.rs
  examples/crd_derive.rs
  kube-derive/Cargo.toml
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
  kube/src/lib.rs
Labels: changelog-add

#1697 feat: Add deprecated argument to derive macro
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add
