Repository kube-rs/kube, pull requests merged in 2025-03, with the labels that each got.

#1708 Add kube::Api::get_metadata_opt_with
  kube-client/src/api/core_methods.rs
Labels: changelog-add

#1713 kube-runtime: fix exponential backoff max times
  kube-runtime/src/watcher.rs
Labels: changelog-fix

#1710 Add common wait conditions for Deployments, LoadBalancer Services, and Ingress
  kube-runtime/Cargo.toml
  kube-runtime/src/wait.rs
Labels: changelog-add

#1707 add `valid_until` to Client
  kube-client/src/client/auth/mod.rs
  kube-client/src/client/builder.rs
  kube-client/src/client/config_ext.rs
  kube-client/src/client/mod.rs
Labels: changelog-add

#1716 kube-runtime: make ExponentialBackoff public
  kube-runtime/src/watcher.rs
Labels: changelog-add

#1718 Bump `json-patch` to 4 use bundled `jsonptr` to 0.7
  Cargo.toml
  examples/Cargo.toml
  examples/admission_controller.rs
  kube-core/Cargo.toml
  kube-core/src/admission.rs
  kube-runtime/Cargo.toml
  kube-runtime/src/finalizer.rs
Labels: dependencies, changelog-change

#1704 `CustomResource` derive; allow `status` attribute to take a path
  examples/crd_derive_multi.rs
  kube-derive/src/custom_resource.rs
Labels: changelog-fix

#1717 deps: remove hyper-rustls/ring feature
  e2e/Cargo.toml
  examples/Cargo.toml
  kube-client/Cargo.toml
  kube-client/src/client/auth/oidc.rs
  kube/Cargo.toml
Labels: changelog-change

#1720 ring/aws-lc-rs docs and feature tweak
  README.md
  kube-client/Cargo.toml
Labels: changelog-exclude

#1721 allow releasing 1.0 in the future
  kube-client/Cargo.toml
  kube-core/Cargo.toml
  kube-derive/Cargo.toml
  kube-runtime/Cargo.toml
Labels: changelog-exclude

#1722 use static async fn in trait
  Cargo.toml
  kube-runtime/Cargo.toml
  kube-runtime/src/watcher.rs
Labels: changelog-exclude

#1725 remove resolved cargo-deny config
  deny.toml
Labels: changelog-exclude

#1733 docs: Adjust #[kube(scale(...)] doc example
  kube-derive/src/lib.rs
Labels: docs, changelog-fix
