Repository kube-rs/kube, pull requests merged in 2025-04, with the labels that each got.

#1734 feat(deps): enable `hyper-util/tracing` feature flag
  examples/Cargo.toml
  kube-client/Cargo.toml
Labels: changelog-add

#1738 Remove deprecated `watcher::Event` `into_iter_*` methods
  kube-runtime/src/watcher.rs
Labels: changelog-remove

#1747 Add suffix to generated struct by `CELSchema`
  examples/crd_derive_schema.rs
  kube-derive/src/cel_schema.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-fix

#1749 Allow schemars validate attribute in `CELSchema`
  kube-derive/src/cel_schema.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-fix

#1752 Update hyper-util for enabled feature
  Cargo.toml
Labels: dependencies, changelog-exclude

#1753 Fix a clippy lint and update deny allow on optional webpki-roots
  deny.toml
  kube-runtime/src/reflector/store.rs
Labels: changelog-exclude

#1750 Support additional `x-kubernetes-*` schema extensions
  Cargo.toml
  examples/crd_derive_schema.rs
  kube-core/Cargo.toml
  kube-core/src/cel.rs
  kube-core/src/lib.rs
  kube-derive/src/cel_schema.rs
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
  kube/src/lib.rs
Labels: changelog-change
