Repository kube-rs/kube, pull requests merged in 2025-05, with the labels that each got.

#1754 Permit literal string validation for CEL expressions
  examples/crd_derive_schema.rs
  kube-core/src/cel.rs
  kube-derive/src/cel_schema.rs
  kube-derive/src/custom_resource.rs
  kube-derive/src/lib.rs
  kube-derive/tests/crd_schema_test.rs
Labels: changelog-add

#1756 Bump `k8s-openapi` to `0.25.0`
  .devcontainer/Dockerfile
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  Cargo.toml
  README.md
  deny.toml
  kube-derive/src/custom_resource.rs
  kube-runtime/src/wait.rs
Labels: changelog-change

#1758 fix: resolve conflict with schemars preserve_order feature
  examples/Cargo.toml
  justfile
  kube-core/src/cel.rs
Labels: changelog-fix

#1764 fix(derive): Emit schemars crate attribute
  kube-derive/src/custom_resource.rs
Labels: changelog-fix
